const dotenv = require('dotenv');
dotenv.config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const User = require('../models/User');
const Product = require('../models/Product');
const Category = require('../models/Category');

const categories = [
  { name: 'Mobiles', slug: 'mobiles', icon: 'Smartphone', tag: 'Top Brand', description: 'Smartphones, tablets and accessories' },
  { name: 'Televisions', slug: 'televisions', icon: 'Tv', tag: '4K Smart', description: 'Smart TVs and home entertainment' },
  { name: 'Air Conditioners', slug: 'air-conditioners', icon: 'Wind', tag: '5-Star Inverter', description: 'Energy-efficient cooling solutions' },
  { name: 'Refrigerators', slug: 'refrigerators', icon: 'RefrigeratorIcon', tag: 'Frost Free', description: 'Smart refrigerators and cooling appliances' },
  { name: 'Washing Machines', slug: 'washing-machines', icon: 'WashingMachine', tag: 'Front Load', description: 'Fully automatic and semi-automatic washers' },
  { name: 'Laptops', slug: 'laptops', icon: 'Laptop', tag: 'Latest Gen', description: 'Laptops, ultrabooks and computers' },
  { name: 'Audio', slug: 'audio', icon: 'Headphones', tag: 'Dolby Atmos', description: 'Headphones, speakers and soundbars' },
  { name: 'Kitchen', slug: 'kitchen', icon: 'UtensilsCrossed', tag: 'Smart Living', description: 'Kitchen appliances and tools' },
  { name: 'Wearables', slug: 'wearables', icon: 'Watch', tag: 'AMOLED', description: 'Smartwatches and fitness bands' },
];

const products = [
  // Mobiles
  {
    name: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 256GB)',
    brand: 'Samsung',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'Galaxy AI is here. 200MP camera, built-in S Pen, Snapdragon 8 Gen 3 for Galaxy, and flat 6.8-inch Dynamic AMOLED 2X display with Titanium armor frame.',
    price: 144999,
    discountPrice: 129999,
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
      { key: 'RAM', value: '12GB LPDDR5X' },
      { key: 'Storage', value: '256GB UFS 4.0' },
      { key: 'Display', value: '6.8" Dynamic AMOLED 2X, 120Hz' },
      { key: 'Camera', value: '200MP + 12MP + 10MP + 50MP' },
      { key: 'Battery', value: '5000mAh, 45W Fast Charging' },
      { key: 'OS', value: 'Android 14 + One UI 6.1' },
    ],
    features: ['Snapdragon 8 Gen 3 Processor', '200MP Quad Telephoto Camera', 'Built-in S-Pen with Air Actions', '5000mAh Battery with 45W Fast Charging', '7 Years OS & Security Updates'],
    rating: 4.9,
    reviewCount: 584,
    sku: 'SAM-S24U-256',
    isFeatured: true,
    badge: 'Best Seller',
  },
  {
    name: 'Apple iPhone 16 Pro (Natural Titanium, 128GB)',
    brand: 'Apple',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: 'A18 Pro chip, Camera Control button, 48MP Fusion camera with 5x Telephoto optical zoom, grade 5 titanium design with 6.3-inch Super Retina XDR display.',
    price: 129900,
    discountPrice: 119900,
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Apple A18 Pro Bionic' },
      { key: 'RAM', value: '8GB' },
      { key: 'Storage', value: '128GB' },
      { key: 'Display', value: '6.3" Super Retina XDR, ProMotion 120Hz' },
      { key: 'Camera', value: '48MP Fusion + 12MP Ultrawide + 12MP 5x Telephoto' },
      { key: 'Battery', value: 'Up to 27 hours video' },
      { key: 'OS', value: 'iOS 18' },
    ],
    features: ['Apple A18 Pro Bionic Chip', '48MP Fusion Camera + 5x Telephoto Zoom', 'Camera Control Dedicated Sensor Button', 'All-Day Battery Life with MagSafe 25W'],
    rating: 4.9,
    reviewCount: 742,
    sku: 'APL-IP16P-128',
    isFeatured: true,
    badge: 'Trending',
  },
  {
    name: 'OnePlus 12 5G (Silky Black, 16GB RAM, 512GB)',
    brand: 'OnePlus',
    category: 'Mobiles',
    subcategory: 'Smartphones',
    description: '4th Gen Hasselblad Camera System for Mobile, 2K 120Hz ProXDR display, 5400mAh battery with blazing 100W SUPERVOOC and 50W AIRVOOC wireless charging.',
    price: 69999,
    discountPrice: 64999,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Qualcomm Snapdragon 8 Gen 3' },
      { key: 'RAM', value: '16GB LPDDR5X' },
      { key: 'Storage', value: '512GB UFS 4.0' },
      { key: 'Display', value: '6.82" LTPO AMOLED 2K 120Hz' },
      { key: 'Camera', value: '50MP Sony LYT-808 + 64MP Periscope + 48MP Ultrawide' },
      { key: 'Battery', value: '5400mAh, 100W SUPERVOOC' },
    ],
    features: ['Qualcomm Snapdragon 8 Gen 3', '50MP Sony LYT-808 Main Sensor', '100W SUPERVOOC Flash Charge in 26m', 'Dual Cryo-velocity VC Cooling System'],
    rating: 4.8,
    reviewCount: 390,
    sku: 'OP-12-16-512',
    isFeatured: false,
    badge: 'Popular',
  },
  {
    name: 'Apple iPad Air 11-inch M2 (Starlight, 128GB Wi-Fi)',
    brand: 'Apple',
    category: 'Mobiles',
    subcategory: 'Tablets',
    description: 'Supercharged by the Apple M2 chip with Liquid Retina display, landscape 12MP front camera with Center Stage, and Apple Pencil Pro support.',
    price: 64900,
    discountPrice: 59900,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Apple M2 8-core CPU' },
      { key: 'RAM', value: '8GB' },
      { key: 'Storage', value: '128GB' },
      { key: 'Display', value: '11" Liquid Retina, 2360×1640' },
    ],
    features: ['Apple M2 8-core CPU & 10-core GPU', '11" Liquid Retina with P3 Wide Color', 'Support for Apple Pencil Pro & Magic Keyboard', 'Wi-Fi 6E Superfast Connectivity'],
    rating: 4.8,
    reviewCount: 215,
    sku: 'APL-IPAD-AIR-M2',
    isFeatured: true,
    badge: 'Top Pick',
  },
  // Televisions
  {
    name: 'Sony BRAVIA 65" 4K Ultra HD Smart Google TV (XR-65X90L)',
    brand: 'Sony',
    category: 'Televisions',
    subcategory: '4K Smart TVs',
    description: 'Cognitive Processor XR delivers natural contrast and deep blacks with Full Array LED. Google TV with hands-free voice control, Dolby Vision & Atmos.',
    price: 179900,
    discountPrice: 124990,
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Screen Size', value: '65 inches' },
      { key: 'Resolution', value: '4K Ultra HD (3840×2160)' },
      { key: 'Display Type', value: 'Full Array LED' },
      { key: 'Refresh Rate', value: '120Hz (Native)' },
      { key: 'HDR', value: 'Dolby Vision, HDR10, HLG' },
      { key: 'Audio', value: 'Dolby Atmos, 50W' },
      { key: 'Smart Platform', value: 'Google TV' },
    ],
    features: ['Cognitive Processor XR with Full Array LED', '4K 120Hz VRR & ALLM for PlayStation 5', 'Dolby Vision & Dolby Atmos 3D Audio', 'Hands-Free Google Assistant & Apple AirPlay'],
    rating: 4.9,
    reviewCount: 420,
    sku: 'SONY-XR65X90L',
    isFeatured: true,
    badge: 'Mega Deal',
  },
  {
    name: 'Samsung 55" Crystal 4K Vivid Pro Ultra HD Smart TV',
    brand: 'Samsung',
    category: 'Televisions',
    subcategory: '4K Smart TVs',
    description: 'PurColor technology with Crystal Processor 4K, Motion Xcelerator, SolarCell Remote, Q-Symphony sound sync, and Samsung Knox Security.',
    price: 68900,
    discountPrice: 43990,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Screen Size', value: '55 inches' },
      { key: 'Resolution', value: '4K Crystal UHD' },
      { key: 'Refresh Rate', value: '60Hz' },
      { key: 'HDR', value: 'HDR10+' },
      { key: 'Smart Platform', value: 'Tizen OS 8.0' },
    ],
    features: ['Crystal Processor 4K Upscaling', 'PurColor with HDR10+ Support', 'Q-Symphony Sound Synchronization', 'SolarCell Eco Remote Control'],
    rating: 4.8,
    reviewCount: 690,
    sku: 'SAM-55CU7700',
    isFeatured: true,
    badge: 'Best Value',
  },
  {
    name: 'LG 50" 4K UHD Smart WebOS TV (50UT80006LA)',
    brand: 'LG',
    category: 'Televisions',
    subcategory: '4K Smart TVs',
    description: 'LG α5 AI Processor 4K with webOS 24, ThinQ AI voice recognition, Magic Remote, FILMMAKER MODE, and Dolby Vision IQ & Atmos.',
    price: 49990,
    discountPrice: 36990,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Screen Size', value: '50 inches' },
      { key: 'Resolution', value: '4K UHD' },
      { key: 'Processor', value: 'α5 AI Processor 4K Gen7' },
      { key: 'Smart Platform', value: 'webOS 24' },
    ],
    features: ['α5 AI Gen7 Processor', 'FILMMAKER MODE Certified', 'Magic Remote Included', 'ThinQ AI & Google Assistant'],
    rating: 4.7,
    reviewCount: 318,
    sku: 'LG-50UT80006',
    isFeatured: false,
    badge: 'Top Rated',
  },
  // Air Conditioners
  {
    name: 'Daikin 1.5 Ton 5-Star Wi-Fi Inverter Split AC (FTKF50UV)',
    brand: 'Daikin',
    category: 'Air Conditioners',
    subcategory: 'Split ACs',
    description: 'Daikin Inverter Split AC with PM 2.5 filter, intelligent temperature sensing, Coanda Airflow for even cooling, eco-friendly R-32 refrigerant.',
    price: 49990,
    discountPrice: 38990,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '1.5 Ton' },
      { key: 'Star Rating', value: '5 Star BEE 2024' },
      { key: 'Type', value: 'Split Inverter AC' },
      { key: 'Refrigerant', value: 'R-32 (Eco-friendly)' },
      { key: 'Warranty', value: '1 Year + 10 Year Compressor' },
    ],
    features: ['PM 2.5 Filter for Air Purification', 'Coanda Airflow Technology', 'Wi-Fi Smart Control via App', 'R-32 Eco-Friendly Refrigerant', 'Inverter Compressor 10-Year Warranty'],
    rating: 4.8,
    reviewCount: 520,
    sku: 'DAI-FTKF50UV',
    isFeatured: true,
    badge: '5 Star',
  },
  {
    name: 'Voltas 1.5 Ton 4-Star Smart Inverter Split AC (184V XTRA ADJ)',
    brand: 'Voltas',
    category: 'Air Conditioners',
    subcategory: 'Split ACs',
    description: 'Voltas XTRA ADJ Series with multi-stage dust filtration, auto-restart after power cut, turbo cool mode, and intelligent cooling diagnostics.',
    price: 42990,
    discountPrice: 33990,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1590756254933-2873d72a83b6?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1590756254933-2873d72a83b6?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '1.5 Ton' },
      { key: 'Star Rating', value: '4 Star' },
      { key: 'Type', value: 'Split Inverter AC' },
    ],
    features: ['Multi-Stage Dust Filtration', 'Auto-Restart after Power Cut', 'Turbo Cool Mode', 'Sleep Mode for Quiet Operation'],
    rating: 4.6,
    reviewCount: 380,
    sku: 'VOL-184VXTRA',
    isFeatured: false,
    badge: 'Value Pick',
  },
  {
    name: 'LG 1 Ton 5-Star Wi-Fi Dual Inverter Split AC (PS-Q12YNZE)',
    brand: 'LG',
    category: 'Air Conditioners',
    subcategory: 'Split ACs',
    description: 'LG Dual Inverter Compressor with 10 Year warranty, convertible 5-in-1 cooling, AI ThinQ control, Ocean Black Protection for all-weather durability.',
    price: 39990,
    discountPrice: 32990,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '1 Ton' },
      { key: 'Star Rating', value: '5 Star' },
      { key: 'Compressor', value: 'Dual Inverter' },
    ],
    features: ['Dual Inverter Compressor', 'Convertible 5-in-1 Cooling', 'AI ThinQ App Control', 'Ocean Black Protection'],
    rating: 4.8,
    reviewCount: 290,
    sku: 'LG-PSQ12YNZE',
    isFeatured: true,
    badge: 'Energy Saver',
  },
  // Refrigerators
  {
    name: 'LG 655L Side-by-Side Refrigerator with InstaView Door-in-Door',
    brand: 'LG',
    category: 'Refrigerators',
    subcategory: 'Side-by-Side',
    description: 'InstaView Door-in-Door with knock-to-see-inside technology, Linear Cooling, Door Cooling+, Fresh 0 zone drawer, SmartDiagnosis, and Hygiene Fresh+ filter.',
    price: 159990,
    discountPrice: 109990,
    stock: 6,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '655 Litres' },
      { key: 'Type', value: 'Side-by-Side' },
      { key: 'Star Rating', value: '5 Star' },
      { key: 'Compressor', value: 'Linear Inverter' },
    ],
    features: ['InstaView Knock-to-See Technology', 'Linear Cooling ±0.5°C Precision', 'Door Cooling+ for Even Temperature', 'Hygiene Fresh+ Air Filter', '10-Year Compressor Warranty'],
    rating: 4.8,
    reviewCount: 218,
    sku: 'LG-GC-B247SVZV',
    isFeatured: true,
    badge: 'Premium',
  },
  {
    name: 'Samsung 324L Double Door Digital Inverter Refrigerator',
    brand: 'Samsung',
    category: 'Refrigerators',
    subcategory: 'Double Door',
    description: 'Digital Inverter Technology with All-Around Cooling, Twin Cooling Plus, precise temperature control, SpaceMax Technology for maximum storage.',
    price: 42990,
    discountPrice: 33990,
    stock: 28,
    images: ['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '324 Litres' },
      { key: 'Type', value: 'Double Door Frost Free' },
      { key: 'Star Rating', value: '3 Star' },
    ],
    features: ['Digital Inverter Technology', 'All-Around Cooling', 'Twin Cooling Plus', 'SpaceMax Maximized Storage'],
    rating: 4.5,
    reviewCount: 410,
    sku: 'SAM-RT34B4513DX',
    isFeatured: false,
    badge: 'Best Seller',
  },
  {
    name: 'Whirlpool 240L Frost Free Double Door 3-Star Refrigerator',
    brand: 'Whirlpool',
    category: 'Refrigerators',
    subcategory: 'Double Door',
    description: 'Intellifresh Technology with Adaptive Intelligent Technology maintains freshness, Microblock technology prevents 99.9% bacteria growth.',
    price: 29990,
    discountPrice: 23990,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '240 Litres' },
      { key: 'Type', value: 'Frost Free Double Door' },
      { key: 'Star Rating', value: '3 Star' },
    ],
    features: ['Intellifresh Technology', 'Adaptive Intelligent Technology', 'Microblock Anti-Bacterial', '6th Sense Power Cool'],
    rating: 4.4,
    reviewCount: 580,
    sku: 'WHP-NEO278H',
    isFeatured: false,
    badge: 'Value Pick',
  },
  // Washing Machines
  {
    name: 'Bosch 10 Kg Front Load Fully Automatic Washing Machine (WAJ28262IN)',
    brand: 'Bosch',
    category: 'Washing Machines',
    subcategory: 'Front Load',
    description: 'EcoSilence Drive motor for ultra-quiet operation, Anti-Vibration Design, i-DOS intelligent automatic detergent dispensing, SpeedPerfect for faster wash.',
    price: 74990,
    discountPrice: 55990,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '10 Kg' },
      { key: 'Type', value: 'Front Load Fully Automatic' },
      { key: 'Spin Speed', value: '1200 RPM' },
      { key: 'Energy Rating', value: 'A++' },
    ],
    features: ['EcoSilence Drive Motor', 'i-DOS Auto Detergent Dispensing', 'SpeedPerfect 65% Faster Wash', 'Anti-Vibration Design', '1200 RPM High Spin Speed'],
    rating: 4.8,
    reviewCount: 320,
    sku: 'BOSCH-WAJ28262',
    isFeatured: true,
    badge: 'Premium',
  },
  {
    name: 'Samsung 8 Kg Front Load Washing Machine with Inverter (WW80T4040CX)',
    brand: 'Samsung',
    category: 'Washing Machines',
    subcategory: 'Front Load',
    description: 'Digital Inverter Motor with Bubble Soak and AddWash door, SmartCheck error monitoring, AI Control for personalized cycles, and 1200 RPM spin.',
    price: 52990,
    discountPrice: 39990,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '8 Kg' },
      { key: 'Type', value: 'Front Load Fully Automatic' },
      { key: 'Motor', value: 'Digital Inverter' },
    ],
    features: ['Digital Inverter Motor', 'Bubble Soak Technology', 'AddWash Door for Mid-Cycle Additions', 'SmartCheck Error Monitoring'],
    rating: 4.6,
    reviewCount: 475,
    sku: 'SAM-WW80T4040',
    isFeatured: false,
    badge: 'Top Seller',
  },
  {
    name: 'LG 7 Kg Top Load Washing Machine with Wi-Fi (T70SKSF4Z)',
    brand: 'LG',
    category: 'Washing Machines',
    subcategory: 'Top Load',
    description: 'TurboDrum technology removes tough stains, Smart Inverter Motor, 6 Motion DD Direct Drive, NFC Smart Diagnosis, and Water Plus technology.',
    price: 34990,
    discountPrice: 28990,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '7 Kg' },
      { key: 'Type', value: 'Top Load Fully Automatic' },
      { key: 'Motor', value: 'Smart Inverter' },
    ],
    features: ['TurboDrum Technology', '6 Motion DD Technology', 'Smart Inverter Motor', 'Wi-Fi & Smart Diagnosis'],
    rating: 4.5,
    reviewCount: 620,
    sku: 'LG-T70SKSF4Z',
    isFeatured: false,
    badge: 'Value Pick',
  },
  // Laptops
  {
    name: 'Apple MacBook Pro 14" M3 Pro (512GB SSD, 18GB RAM)',
    brand: 'Apple',
    category: 'Laptops',
    subcategory: 'Premium Laptops',
    description: 'M3 Pro chip with 12-core CPU and 18-core GPU, Liquid Retina XDR display with ProMotion 120Hz, 18GB unified memory, up to 22 hours battery life.',
    price: 199900,
    discountPrice: 174900,
    stock: 7,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Apple M3 Pro 12-core CPU' },
      { key: 'RAM', value: '18GB Unified Memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14.2" Liquid Retina XDR 120Hz' },
      { key: 'Battery', value: 'Up to 22 Hours' },
      { key: 'GPU', value: '18-core GPU' },
    ],
    features: ['Apple M3 Pro 12-core CPU', '18-core GPU for Pro Workflows', 'Liquid Retina XDR ProMotion Display', '22 Hour Battery Life', 'MagSafe 3 Charging'],
    rating: 4.9,
    reviewCount: 280,
    sku: 'APL-MBP14-M3P',
    isFeatured: true,
    badge: 'Premium',
  },
  {
    name: 'Dell XPS 15 (9560) Intel Core Ultra 7 165H (32GB RAM, 1TB SSD)',
    brand: 'Dell',
    category: 'Laptops',
    subcategory: 'Premium Laptops',
    description: 'Intel Core Ultra 7 with 3.5K OLED InfinityEdge display, NVIDIA RTX 4060, CNC aluminum chassis, Windows 11 Pro, Thunderbolt 4 and USB4.',
    price: 174990,
    discountPrice: 149990,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Intel Core Ultra 7 165H' },
      { key: 'RAM', value: '32GB DDR5' },
      { key: 'Storage', value: '1TB PCIe NVMe SSD' },
      { key: 'Display', value: '15.6" OLED 3.5K 120Hz' },
      { key: 'GPU', value: 'NVIDIA GeForce RTX 4060' },
    ],
    features: ['Intel Core Ultra 7 165H AI Processor', 'NVIDIA RTX 4060 8GB GPU', '3.5K OLED InfinityEdge 120Hz', 'Thunderbolt 4 x2 Ports', 'CNC Aluminum Premium Build'],
    rating: 4.8,
    reviewCount: 180,
    sku: 'DELL-XPS15-9560',
    isFeatured: true,
    badge: 'Editor\'s Choice',
  },
  {
    name: 'Lenovo IdeaPad Slim 5 (16IH8) Intel Core i5-13420H (16GB, 512GB SSD)',
    brand: 'Lenovo',
    category: 'Laptops',
    subcategory: 'Everyday Laptops',
    description: 'Intel Core i5-13th Gen with 16GB RAM, 512GB SSD, 16-inch WUXGA IPS Anti-glare display, Intel Iris Xe Graphics, Windows 11 Home, and backlit keyboard.',
    price: 65990,
    discountPrice: 54990,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Processor', value: 'Intel Core i5-13420H' },
      { key: 'RAM', value: '16GB DDR5' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '16" WUXGA 1920×1200 IPS' },
    ],
    features: ['Intel Core i5 13th Gen', '16" WUXGA Anti-Glare IPS', 'Backlit Keyboard', 'Rapid Charge (80% in 1 Hour)', 'Windows 11 Home Pre-installed'],
    rating: 4.5,
    reviewCount: 640,
    sku: 'LEN-IPS5-16IH8',
    isFeatured: false,
    badge: 'Best Value',
  },
  // Audio
  {
    name: 'Sony WH-1000XM5 Wireless Industry Leading Noise Cancelling Headphones',
    brand: 'Sony',
    category: 'Audio',
    subcategory: 'Headphones',
    description: 'Industry-leading noise cancellation with dual processors V1 and HD QN1, 30-hour battery, Multipoint Bluetooth connection, and Speak-to-Chat technology.',
    price: 34990,
    discountPrice: 26990,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Driver', value: '30mm, Carbon Fiber Composite' },
      { key: 'Battery', value: '30 Hours (ANC On)' },
      { key: 'Bluetooth', value: '5.2 Multipoint' },
      { key: 'Noise Cancellation', value: 'Dual Processor V1 + HD QN1' },
    ],
    features: ['Industry-Leading Noise Cancellation', 'Dual Processor Technology', '30-Hour Battery Life', 'Multipoint Connection (2 Devices)', 'Speak-to-Chat & Quick Attention'],
    rating: 4.9,
    reviewCount: 1024,
    sku: 'SONY-WH1000XM5',
    isFeatured: true,
    badge: 'Award Winner',
  },
  {
    name: 'JBL PartyBox 710 Portable Party Speaker with Powerful Sound',
    brand: 'JBL',
    category: 'Audio',
    subcategory: 'Speakers',
    description: 'JBL Pro Sound with 800W RMS Power, RGB LED lights, IPX4 water resistance, Guitar & Mic inputs, 12-Hour battery, USB playback and wireless Bluetooth 5.3.',
    price: 59999,
    discountPrice: 42999,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Power', value: '800W RMS' },
      { key: 'Battery', value: '12 Hours' },
      { key: 'Water Resistance', value: 'IPX4' },
      { key: 'Bluetooth', value: '5.3' },
    ],
    features: ['800W RMS JBL Pro Sound', 'RGB Star Light Effect', 'IPX4 Water Resistance', 'Guitar & Mic Inputs', '12-Hour Battery Life'],
    rating: 4.7,
    reviewCount: 380,
    sku: 'JBL-PARTYBOX710',
    isFeatured: true,
    badge: 'Party King',
  },
  {
    name: 'Samsung HW-Q990D 11.1.4ch Soundbar with Dolby Atmos',
    brand: 'Samsung',
    category: 'Audio',
    subcategory: 'Soundbars',
    description: '11.1.4 channel with wireless subwoofer, rear speakers, SpaceFit Sound Pro, Q-Symphony 3.0, Dolby Atmos & DTS:X, 656W total output.',
    price: 129990,
    discountPrice: 89990,
    stock: 5,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Channels', value: '11.1.4' },
      { key: 'Total Output', value: '656W' },
      { key: 'Audio Formats', value: 'Dolby Atmos, DTS:X' },
    ],
    features: ['11.1.4 Channel Immersive Audio', 'Q-Symphony 3.0 TV Sync', 'SpaceFit Sound Pro Auto-Calibration', 'Wireless Subwoofer & Rear Speakers'],
    rating: 4.8,
    reviewCount: 156,
    sku: 'SAM-HWQ990D',
    isFeatured: false,
    badge: 'Premium',
  },
  // Kitchen
  {
    name: 'Philips 3000W Digital Air Fryer XXL 7.3L (HD9270/91)',
    brand: 'Philips',
    category: 'Kitchen',
    subcategory: 'Air Fryers',
    description: 'Rapid Air Technology for healthiest cooking, 7.3L family-size capacity, Fat Removal Technology up to 90% less fat, 13 preset programs, easy clean.',
    price: 24995,
    discountPrice: 16995,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '7.3 Litres' },
      { key: 'Power', value: '3000W' },
      { key: 'Programs', value: '13 Preset Programs' },
    ],
    features: ['Rapid Air Technology', '7.3L XXL Family Capacity', '90% Less Fat Cooking', '13 Preset Programs', 'Dishwasher Safe Parts'],
    rating: 4.7,
    reviewCount: 890,
    sku: 'PHL-HD9270',
    isFeatured: true,
    badge: 'Healthy Choice',
  },
  {
    name: 'Bosch Serie 6 Fully Automatic Coffee Machine (TIS30521GB)',
    brand: 'Bosch',
    category: 'Kitchen',
    subcategory: 'Coffee Machines',
    description: 'One-touch coffee, Aroma Grinder with 5 settings, Sensoflow heating system, MilkMagic frother, Calc\'nClean automatic cleaning program.',
    price: 89990,
    discountPrice: 62990,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Type', value: 'Fully Automatic Bean-to-Cup' },
      { key: 'Grinder', value: 'Aroma Grinder 5 Settings' },
      { key: 'Pump Pressure', value: '15 Bar' },
    ],
    features: ['One-Touch Espresso & Cappuccino', 'Aroma Grinder with 5 Settings', 'MilkMagic Automatic Frother', 'Sensoflow Temperature System', '15 Bar Pump Pressure'],
    rating: 4.8,
    reviewCount: 120,
    sku: 'BOSCH-TIS30521',
    isFeatured: false,
    badge: 'Coffee Lover',
  },
  {
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 5.7L',
    brand: 'Instant Pot',
    category: 'Kitchen',
    subcategory: 'Pressure Cookers',
    description: '7 appliances in 1: Pressure Cooker, Slow Cooker, Rice Cooker, Steamer, Sauté, Yogurt Maker, and Warmer. 5.7L for up to 8 servings, 14 smart programs.',
    price: 12999,
    discountPrice: 8999,
    stock: 55,
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Capacity', value: '5.7 Litres' },
      { key: 'Functions', value: '7-in-1' },
      { key: 'Programs', value: '14 Smart Programs' },
    ],
    features: ['7-in-1 Multi-Cooker', '14 Smart One-Touch Programs', 'Up to 70% Faster Cooking', 'Steam Release Handle', '10 Proven Safety Features'],
    rating: 4.6,
    reviewCount: 1240,
    sku: 'IP-DUO-5.7L',
    isFeatured: false,
    badge: 'Most Loved',
  },
  // Wearables
  {
    name: 'Apple Watch Ultra 2 (49mm, Titanium, Ocean Band)',
    brand: 'Apple',
    category: 'Wearables',
    subcategory: 'Smartwatches',
    description: 'Most rugged Apple Watch with 49mm titanium case, precision dual-frequency GPS, depth gauge to 100m, Trail Loop & Ocean Band, S9 SiP chip, 60-hour battery.',
    price: 89900,
    discountPrice: 83900,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Case Size', value: '49mm' },
      { key: 'Material', value: 'Titanium' },
      { key: 'Water Resistance', value: '100m WR + EN13319' },
      { key: 'Battery', value: 'Up to 60 Hours (Low Power)' },
      { key: 'Chip', value: 'Apple S9 SiP' },
    ],
    features: ['Dual-Frequency GPS for Precision', '100m Water Resistance for Diving', 'Emergency SOS via Satellite', 'Ultra-Loud 86dB Siren', '60-Hour Battery in Low Power Mode'],
    rating: 4.9,
    reviewCount: 312,
    sku: 'APL-WATCH-U2',
    isFeatured: true,
    badge: 'Ultra Premium',
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic 47mm (Black, Bluetooth)',
    brand: 'Samsung',
    category: 'Wearables',
    subcategory: 'Smartwatches',
    description: 'Iconic rotating bezel, sapphire crystal glass, Exynos W930 chip, Advanced Sleep Coaching, Body Composition analysis, BioActive Sensor, 40-hour battery.',
    price: 41999,
    discountPrice: 32999,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Case Size', value: '47mm' },
      { key: 'Display', value: '1.5" Super AMOLED 480×480' },
      { key: 'Processor', value: 'Exynos W930 Dual Core' },
      { key: 'Battery', value: '425mAh, 40 Hours' },
    ],
    features: ['Rotating Bezel Navigation', 'Sapphire Crystal Glass', 'Advanced Sleep Coaching', 'Body Composition Analyzer', 'BioActive Health Sensor'],
    rating: 4.7,
    reviewCount: 480,
    sku: 'SAM-GW6C-47',
    isFeatured: true,
    badge: 'Top Rated',
  },
  {
    name: 'boAt Wave Flex Connect Smart Watch with BT Calling (Black)',
    brand: 'boAt',
    category: 'Wearables',
    subcategory: 'Smartwatches',
    description: 'Bluetooth Calling with Loud Speaker, 1.83" HD display, 100+ sports modes, SpO2 and heart rate monitoring, 7-day battery, IP68 water resistance.',
    price: 3999,
    discountPrice: 1499,
    stock: 150,
    images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Display', value: '1.83" HD' },
      { key: 'Battery', value: '7 Days' },
      { key: 'Water Resistance', value: 'IP68' },
    ],
    features: ['Bluetooth Calling with Speaker', '1.83" HD Display', '100+ Sports & Activity Modes', 'SpO2 & Heart Rate Monitor', 'IP68 Water Resistance'],
    rating: 4.1,
    reviewCount: 2890,
    sku: 'BOAT-WAVEFLEX',
    isFeatured: false,
    badge: 'Budget Pick',
  },
];

const seedDB = async () => {
  try {
    await connectDB();
    console.log('🌱 Starting database seed...');

    // Clear existing data
    await User.deleteMany({});
    await Product.deleteMany({});
    await Category.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Create admin user
    const adminUser = await User.create({
      fullName: 'Value Plus Admin',
      email: 'admin@valueplus.in',
      phone: '9999999999',
      password: 'Admin@1234',
      role: 'admin',
    });
    console.log(`✅ Admin user created: ${adminUser.email}`);
    console.log('   📋 Admin credentials: admin@valueplus.in / Admin@1234');

    // Create a demo user
    await User.create({
      fullName: 'Demo Customer',
      email: 'demo@valueplus.in',
      phone: '8888888888',
      password: 'Demo@1234',
      role: 'user',
    });
    console.log('✅ Demo user created: demo@valueplus.in / Demo@1234');

    // Create categories
    const createdCategories = await Category.insertMany(categories);
    console.log(`✅ Created ${createdCategories.length} categories`);

    // Create products with auto-slug
    let createdCount = 0;
    for (const prod of products) {
      const slugBase = prod.name.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, '-');
      await Product.create({
        ...prod,
        slug: `${slugBase}-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      });
      createdCount++;
    }
    console.log(`✅ Created ${createdCount} products`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('\n📝 Login Credentials:');
    console.log('   Admin: admin@valueplus.in / Admin@1234');
    console.log('   User:  demo@valueplus.in / Demo@1234');
    console.log('\n🚀 Start the backend: npm run dev');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedDB();
